### ISSUE TITLE
improve readme

### ISSUE THREAD

**Issue by physikerwelt** [kaushal2161/Mathaware-Q-A-System#2]
from the readme it's not clear to me what I have to do to use the software.
When I installed all the libraries described in the readme, what would I do next?
How would I check if the installation was successful?
What can I do with the mathqa system?

**Comment by kaushal2161** [comment]
Hello,

After installing all the libraries you have to run the server.
1) CoreNlp server from where it installed 
2) run the flask app from the root directory 

I am outside nw so can't update the read me file but may be this helps.

If any problem in installation you will get errot in flask server.



Regards,
Kaushal.
